/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2025-06-04 02:13:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import kr.smhrd.entity.Member;
import java.util.ArrayList;

public final class Main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("kr.smhrd.entity.Member");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

 	String isLogined = "";
	String title = "<h1 id='title'>";
	Member loginUser = (Member)session.getAttribute("user");
	if(loginUser!=null) {
		title += loginUser.getEmail().split("@")[0]+"님 안녕하세요";
		isLogined = "isLogin";
	} else {
		title += "로그인 한 세션아이디를 출력해주세요";
		isLogined = "";
	}
	title += "</h1>"; 		

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<title>Forty by HTML5 UP</title>\r\n");
      out.write("\t\t<meta charset=\"utf-8\" />\r\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t\t<!--[if lte IE 8]><script src=\"assets/js/ie/html5shiv.js\"></script><![endif]-->\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"resources/assets/css/main.css\" />\r\n");
      out.write("\t\t<!--[if lte IE 9]><link rel=\"stylesheet\" href=\"assets/css/ie9.css\" /><![endif]-->\r\n");
      out.write("\t\t<!--[if lte IE 8]><link rel=\"stylesheet\" href=\"assets/css/ie8.css\" /><![endif]-->\r\n");
      out.write("\t\t<style>\r\n");
      out.write("\t\t\t.hidden {\r\n");
      out.write("\t\t\t\tdisplay: none;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</style>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body class=\"");
      out.print(isLogined);
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Wrapper -->\r\n");
      out.write("\t\t\t<div id=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Header -->\r\n");
      out.write("\t\t\t\t\t<header id=\"header\" class=\"alt\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"index.html\" class=\"logo\"><strong>Forty</strong> <span>by HTML5 UP</span></a>\r\n");
      out.write("\t\t\t\t\t\t<nav>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Q6. 로그인을 한 상태에서는 로그인탭 대신 로그아웃탭과 개인정보수정탭을 출력 -->\r\n");
      out.write("\t\t\t\t\t\t\t");
if(loginUser==null) {
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#menu\">로그인</a>\r\n");
      out.write("\t\t\t\t\t\t\t");
} else {
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"goUpdateMember\">개인정보 수정</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"logout\">로그아웃</a>\r\n");
      out.write("\t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Q7. 개인정보수정 기능 만들기 -->\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Q8. 로그아웃 기능 만들기 -->\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Q9. 관리자 계정(admin)일 때는 회원정보관리 탭 만들기 -->\r\n");
      out.write("\t\t\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t\t</header>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Menu -->\r\n");
      out.write("\t\t\t\t\t<nav id=\"menu\">\t\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"links\">\r\n");
      out.write("\t\t\t\t\t\t<!-- Q3. 로그인 기능 만들기 -->\r\n");
      out.write("\t\t\t\t\t\t\t<li><h5>로그인</h5></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<form action=\"login\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><input type=\"text\"  placeholder=\"Email을 입력하세요\" name=\"email\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><input type=\"password\"  placeholder=\"PW를 입력하세요\" name=\"pw\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><input type=\"submit\" value=\"LogIn\" class=\"button fit\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"actions vertical\">\r\n");
      out.write("\t\t\t\t\t\t<!-- Q1. 회원가입 기능 만들기 -->\r\n");
      out.write("\t\t\t\t\t\t<!-- email, pw, tel, address -->\r\n");
      out.write("\t\t\t\t\t\t\t<li><h5>회원가입</h5></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<form action=\"join\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><input type=\"text\"  placeholder=\"Email을 입력하세요\" name=\"email\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><input type=\"password\"  placeholder=\"PW를 입력하세요\" name=\"pw\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><input type=\"text\"  placeholder=\"전화번호를 입력하세요\" name=\"tel\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><input type=\"text\"  placeholder=\"집주소를 입력하세요\" name=\"address\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><input type=\"submit\" value=\"JoinUs\" class=\"button fit\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</nav>\t\t\t\r\n");
      out.write("\t\t\t\t<!-- Banner -->\r\n");
      out.write("\t\t\t\t\t<section id=\"banner\" class=\"major\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"inner\">\r\n");
      out.write("\t\t\t\t\t\t\t<header class=\"major\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Q4. 로그인 후 로그인한 사용자의 아이디로 바꾸기 -->\r\n");
      out.write("\t\t\t\t\t\t\t<!-- ex) smhrd님 환영합니다.  -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
      out.print(title);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</header>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>게시판을 이용해보세요 ^^<br></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"actions\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"BoardMain.jsp\" class=\"button next scrolly\">게시판 바로가기</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Main -->\r\n");
      out.write("\t\t\t\t\t<div id=\"main\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- One -->\r\n");
      out.write("\t\t\t\t\t\t\t<section id=\"one\" class=\"tiles\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<article>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"image\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"resources/images/pic01.jpg\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<header class=\"major\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h3><a href=\"#\" class=\"link\">HTML</a></h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>홈페이지를 만드는 기초 언어</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</header>\r\n");
      out.write("\t\t\t\t\t\t\t\t</article>\r\n");
      out.write("\t\t\t\t\t\t\t\t<article>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"image\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"resources/images/pic02.jpg\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<header class=\"major\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h3><a href=\"#\" class=\"link\">CSS</a></h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>HTML을 디자인해주는 언어</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</header>\r\n");
      out.write("\t\t\t\t\t\t\t\t</article>\r\n");
      out.write("\t\t\t\t\t\t\t\t<article>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"image\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"resources/images/pic03.jpg\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<header class=\"major\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h3><a href=\"#\" class=\"link\">Servlet/JSP</a></h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>Java를 기본으로 한 웹 프로그래밍 언어/스크립트 언어</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</header>\r\n");
      out.write("\t\t\t\t\t\t\t\t</article>\r\n");
      out.write("\t\t\t\t\t\t\t\t<article>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"image\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"resources/images/pic04.jpg\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<header class=\"major\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h3><a href=\"#\" class=\"link\">JavaScript</a></h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>HTML에 기본적인 로직을 정의할 수 있는 언어</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</header>\r\n");
      out.write("\t\t\t\t\t\t\t\t</article>\r\n");
      out.write("\t\t\t\t\t\t\t\t<article>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"image\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"resources/images/pic05.jpg\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<header class=\"major\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h3><a href=\"#\" class=\"link\">MVC</a></h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>웹 프로젝트 중 가장 많이 사용하는 디자인패턴</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</header>\r\n");
      out.write("\t\t\t\t\t\t\t\t</article>\r\n");
      out.write("\t\t\t\t\t\t\t\t<article>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"image\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"resources/images/pic06.jpg\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<header class=\"major\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h3><a href=\"#\" class=\"link\">Web Project</a></h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>여러분의 최종프로젝트에 웹 기술을 활용하세요!</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</header>\r\n");
      out.write("\t\t\t\t\t\t\t\t</article>\r\n");
      out.write("\t\t\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t\t<!-- Two -->\r\n");
      out.write("\t\t\t\t\t\t\t<section id=\"two\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"inner\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<header class=\"major\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h2>나에게 온 메세지 확인하기</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</header>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"actions\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- Q12. 로그인 이메일 출력! -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- ex) smhrd님에게 온 메시지  -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>로그인을 하세요.</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- Q14. 메시지 전체 삭제 기능 -->\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"button next scrolly\">전체삭제하기</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- Q13. table형태로 나한테 온 메시지만 가져와서 보여주기\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t 번호, 보낸사람, 내용, 시간 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- Q15. 메시지 개별 삭제 기능 -->\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Contact -->\r\n");
      out.write("\t\t\t\t\t<section id=\"contact\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"inner\">\r\n");
      out.write("\t\t\t\t\t\t\t<section>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Q11. 메시지 보내기 기능(메시지는 계속 확인하기 위해서 DB에 저장!) -->\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 다른 사람의 DB에 메시지 저장해보기! -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<form>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"field half first\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"name\">Name</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\"  id=\"name\" placeholder=\"보내는 사람 이름\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"field half\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"email\">Email</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\"  id=\"email\" placeholder=\"받는 사람 이메일\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"field\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"message\">Message</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<textarea  id=\"message\" rows=\"6\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"actions\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><input type=\"submit\" value=\"Send Message\" class=\"special\" /></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><input type=\"reset\" value=\"Clear\" /></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<section class=\"split\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<section>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"contact-method\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"icon alt fa-envelope\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h3>Email</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- Q5. 로그인 한 사용자의 이메일을 출력 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t\t\t\t\t<section>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"contact-method\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"icon alt fa-phone\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h3>Phone</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- Q5. 로그인 한 사용자의 전화번호를 출력 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.tel}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t\t\t\t\t<section>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"contact-method\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"icon alt fa-home\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h3>Address</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- Q5. 로그인 한 사용자의 집주소를 출력 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.address}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t\t\t\t</section>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Footer -->\r\n");
      out.write("\t\t\t\t\t<footer id=\"footer\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"inner\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"icons\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"icon alt fa-twitter\"><span class=\"label\">Twitter</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"icon alt fa-facebook\"><span class=\"label\">Facebook</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"icon alt fa-instagram\"><span class=\"label\">Instagram</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"icon alt fa-github\"><span class=\"label\">GitHub</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"icon alt fa-linkedin\"><span class=\"label\">LinkedIn</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"copyright\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>&copy; Untitled</li><li>Design: <a href=\"https://html5up.net\">HTML5 UP</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</footer>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Scripts -->\r\n");
      out.write("\t\t\t<script src=\"resources/assets/js/jquery.min.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"resources/assets/js/jquery.scrolly.min.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"resources/assets/js/jquery.scrollex.min.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"resources/assets/js/skel.min.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"resources/assets/js/util.js\"></script>\r\n");
      out.write("\t\t\t<!--[if lte IE 8]><script src=\"assets/js/ie/respond.min.js\"></script><![endif]-->\r\n");
      out.write("\t\t\t<script src=\"resources/assets/js/main.js\"></script>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<script>\r\n");
      out.write("\t\t\t\tconst btnLogin = document.querySelector(\"a[href='#menu']\");\r\n");
      out.write("\t\t\t\tconst body = document.getElementsByTagName(\"body\")[0];\r\n");
      out.write("\t\t\t\tconst contact = document.getElementById(\"contact\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\tif(body.classList.contains(\"isLogin\")) {\r\n");
      out.write("\t\t\t\t\tcontact.classList.remove(\"hidden\")\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\tcontact.classList.add(\"hidden\")\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
